# Site settings
title: Romain Richard
email: contact@romain-richard.fr
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.romain-richard.fr" # the base hostname & protocol for your site
twitter_username: _romainrichard
github_username:  everio
googleplus_username:  everio
viadeo_username:  romain.richard14

# Build settings
markdown: kramdown
